# 異常検出システム設定

# データセット
datasets:
  mvtec:
    base_path: "./datasets/development/mvtec_anomaly_detection"
    active_category: "bottle"
  active_type: "mvtec"

# モデル
model:
  type: "PaDiM"
  image_size: [256, 256]
  threshold: 0.5

# パス設定
models:
  save_path: "./models/development"
  openvino_path: "./models/openvino"

# 学習
training:
  batch_size: 64
  epochs: 100
  learning_rate: 0.001
  device: "auto"

# 推論
inference:
  processing_device: "CPU"
  confidence_threshold: 0.5
  auto_save_results: true

# システム
logging:
  log_dir: "./logs"
  level: "INFO"

ui:
  window_size:
    width: 1200
    height: 800

app:
  version: "1.0.0"