# Phase1 MVP開発環境設定
datasets:
  mvtec:
    base_path: "datasets/development/mvtec_anomaly_detection"
    categories: ["bottle", "cable", "capsule", "carpet", "grid", "hazelnut", "leather", "metal_nut", "pill", "screw", "tile", "toothbrush", "transistor", "wood", "zipper"]
    category: "hazelnut"  # デフォルトカテゴリ
    image_size: [256, 256]
    train_val_split: 0.8
    
  # カスタムデータセット
  custom:
    base_path: "datasets/development/custom"
    categories: []  # 動的に検出
    train_ratio: 0.8
    validation_ratio: 0.2
    
  # アクティブ設定
  active_type: "mvtec"  # "mvtec" または "custom"
  active_category: "hazelnut"  # アクティブカテゴリ
    
models:
  save_path: "models/development"
  openvino_path: "models/openvino"
  export_path: "models/export"
  
training:
  # anomalib用基本設定
  model_name: "patchcore"  # シンプルで高精度
  batch_size: 16
  max_epochs: 50
  early_stopping: true
  patience: 10
  learning_rate: 0.001
  
inference:
  model_format: "openvino"
  processing_device: "CPU"
  confidence_threshold: 0.5
  
paths:
  data_root: "datasets/development"
  model_root: "models"
  log_root: "logs"
  config_root: "config"